site_name: Pseudopotential optimization
nav:
  - Home: index.md
  - Tutorial: tutorial.md
theme:
  name: material
  features:
    - content.code.annotate # Enable code annotation
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences